# SPDX-FileCopyrightText: 2023-2026, NORCE Research AS
# SPDX-License-Identifier: GPL-3.0
# pylint: disable=R0912,R0914,R0915,C0302

"""Utility functions for necessary files and variables to run OPM Flow"""

from __future__ import annotations

import os
import pathlib

import numpy as np
from numpy.typing import NDArray

from pyopmnearwell.utils.mako import fill_template

HEADER = (
    "-- Copyright (C) 2023-2026 NORCE Research AS\n"
    "-- This deck was generated by pyopmnearwell https://github.com/cssr-tools/pyopmnearwell\n"
)


def reservoir_files(
    dic,
    **kwargs,
):
    """Write OPM-related files by running Mako templates.

    Args:
        dic (dict): Global dictionary with required parameters
        **kwargs: Possible kwargs are:

            - recalc_grid (bool): Whether to recalculate the ``GRID.INC`` file. Intended
              for ensemble runs, where the saturation functions/geography/etc. do not
              need to be recalculated for each ensemble member. Defaults to True.
            - recalc_tables (bool): Whether to recalculate the ``TABLES.INC`` file.
              Defaults to True.
            - recalc_sections (bool): Whether to recalculate the ``GEOLOGY.INC`` and
              ``FLUXNUM.INC`` files. Defaults to True.
            - inc_folder (pathlib.Path): If any of the mentioned files is not
              recalculated, they are taken from this folder. Defaults to
              ``pathlib.Path("")``.

    Note:
        - All of the ``recalc_*`` options only work for
          ``co2store no_disgas_no_diffusion`` on a ``cake`` grid so far.
        - For other models or grids there will be errors.

    Returns:
        dic (dict): Global dictionary with new added parameters

    """
    inc_folder = pathlib.Path(kwargs.get("inc_folder", pathlib.Path("")))
    recalc_grid = kwargs.get("recalc_grid", True)
    recalc_tables = kwargs.get("recalc_tables", True)
    recalc_sections = kwargs.get("recalc_sections", True)
    dic.update(
        {
            "multpv_file": "MULTPV.INC",
            "grid_file": "GRID.INC",
            "drv_file": "DRV.INC",
            "dx_file": "DX.INC",
            "dy_file": "DY.INC",
            "tables_file": "TABLES.INC",
            "geology_file": "GEOLOGY.INC",
            "fluxnum_file": "FLUXNUM.INC",
        }
    )
    if "fprep" not in dic:
        dic["fprep"] = f"{dic['fol']}/preprocessing"
    if "write" not in dic:
        dic["write"] = 1
    dims = dic["dims"]
    nocells = dic["nocells"]
    grid = dic["grid"]
    xfac = dic["xfac"]
    if xfac != 0:
        dic["xcor"] = np.flip(
            dims[0]
            * (np.exp(np.flip(np.linspace(0, xfac, nocells[0] + 1))) - 1)
            / (np.exp(xfac) - 1)
        )
    elif grid == "tensor2d":
        xcn = dic["xcn"]
        scale = dims[0] / len(xcn)
        dic["xcor"] = np.concatenate(
            (
                [0.0],
                np.concatenate(
                    [
                        (index + np.arange(1, num + 1) / num) * scale
                        for index, num in enumerate(xcn)
                    ]
                ),
            )
        )
    elif grid == "coord2d":
        dic["xcor"] = np.asarray(dic["xcn"])
    else:
        dic["xcor"] = np.linspace(0, dims[0], nocells[0] + 1)
    if dic["removecells"] == 1:
        xcor = dic["xcor"]
        dic["xcor"] = xcor[(0.5 * dic["diameter"] < xcor) | (0 == xcor)]
    nocells[0] = len(dic["xcor"]) - 1
    if recalc_grid:
        if grid == "core":
            handle_core(dic)
        else:
            manage_grid(dic)
    else:
        dic.update(
            {
                "grid_file": f"'{inc_folder / 'GRID.INC'}'",
                "drv_file": f"'{inc_folder / 'DRV.INC'}'",
                "dx_file": f"'{inc_folder / 'DX.INC'}'",
                "dy_file": f"'{inc_folder / 'DY.INC'}'",
            }
        )
    if not recalc_tables:
        dic.update({"tables_file": f"'{inc_folder / 'TABLES.INC'}'"})
    if not recalc_sections:
        dic.update(
            {
                "geology_file": f"'{inc_folder / 'GEOLOGY.INC'}'",
                "multpv_file": f"'{inc_folder / 'MULTPV.INC'}'",
                "fluxnum_file": f"'{inc_folder / 'FLUXNUM.INC'}'",
            }
        )
    rock = dic["rock"]
    increments = np.concatenate(
        [
            np.full(rock_value[4], rock_value[3] / rock_value[4])
            for rock_value in rock
            if len(rock_value) > 3
        ]
    )
    dic["zcor"] = np.concatenate(([0.0], np.cumsum(increments)))
    zcor = dic["zcor"]
    xcor = dic["xcor"]
    dic["z_centers"] = 0.5 * (zcor[:-1] + zcor[1:])
    dic["x_centers"] = 0.5 * (xcor[:-1] + xcor[1:])
    thickness = np.cumsum([rock_value[3] for rock_value in rock if len(rock_value) > 3])
    dic["layers"] = np.sum(
        dic["z_centers"][:, None] > thickness[None, :], axis=1
    ).astype(float)
    var = {"dic": dic}
    filledtemplate: str = fill_template(
        var,
        filename=os.path.join(
            dic["pat"], "templates", dic["model"], f"{dic['template']}.mako"
        ),
    )
    with open(
        os.path.join(dic["fprep"], f"{dic['runname'].upper()}.DATA"),
        "w",
        encoding="utf-8",
    ) as file:
        file.write(filledtemplate)
    if dic["model"] not in ["co2eor", "foam"]:
        if recalc_tables:
            manage_tables(dic)
        if recalc_sections:
            manage_sections(dic)


def generate_fluxnum(dic):
    "Write fluxnum.inc"
    output = ""
    n = 1
    val = dic["layers"][0] + 1

    output += "EQUALS\n"

    for i in range(dic["nocells"][2]):
        if val != dic["layers"][i] + 1:
            spaces_n = "".join([" " for _ in range(dic["whnz"] - len(str(n)))])
            spaces_i = "".join([" " for _ in range(dic["whnz"] - len(str(i)))])
            output += f"FLUXNUM {int(val)} 4* {spaces_n}{n} {spaces_i}{i} /\n"
            val = dic["layers"][i] + 1
            n = i + 1
        elif i == dic["nocells"][2] - 1:
            spaces_n = "".join([" " for _ in range(dic["whnz"] - len(str(n)))])
            spaces_i = "".join([" " for _ in range(dic["whnz"] - len(str(i + 1)))])
            output += f"FLUXNUM {int(dic['layers'][i] + 1)} 4* {spaces_n}{n} {spaces_i}{i+1} /\n"

    if dic["perforations"][0] == 1:
        for i in range(dic["perforations"][1]):
            step = (i + 1) * np.floor(
                dic["nocells"][2] / (dic["perforations"][1] + 1)
            ).astype(int)
            spaces_step = "".join([" " for _ in range(dic["whnz"] - len(str(step)))])

            if dic["grid"] not in ["cartesian", "cpg3d", "coord3d", "tensor3d"]:
                sum_val = np.sum(dic["x_centers"] < dic["perforations"][2])
                output += (
                    f"FLUXNUM {dic['satnum']+1} 1 {sum_val} 2* {spaces_step}{step} "
                    f"{spaces_step}{step} /\n"
                )
            else:
                center = np.ceil(dic["nocells"][1] / 2).astype(int)
                sum_val = np.sum(dic["x_centers"] < dic["perforations"][2])
                output += (
                    f"FLUXNUM {dic['satnum']+1} "
                    f"{center - sum_val} {center + sum_val} "
                    f"{center - sum_val} {center + sum_val} "
                    f"{spaces_step}{step} {spaces_step}{step} /\n"
                )
    output += "/"
    return output


def generate_multpv(dic):
    "Write multpv.inc"
    output = ""

    if dic["grid"] == "core":
        output += "".join(dic["coregeometry"])

    elif dic["template"] in ["hwell", "hwellnoise"]:
        output += "MULTIPLY\n"
        output += (
            f"PORV {dic['pvmult']} 4* {dic['nocells'][2]} {dic['nocells'][2]} /  \n"
        )
        output += "/\n"

    elif (
        dic["grid"] != "cartesian"
        and dic["grid"] != "cpg3d"
        and dic["grid"] != "tensor3d"
        and dic["grid"] != "coord3d"
    ):
        value = dic["pvmult"] / (dic["xcor"][-1] - dic["xcor"][-2])
        output += "MULTIPLY\n"
        output += f"PORV {value} {dic['nocells'][0]} {dic['nocells'][0]} 1 1 2* /\n"
        output += "/\n"

    else:
        nocells = dic["nocells"]
        pvmult = dic["pvmult"]
        xcorc = dic["xcorc"]

        def multpv_block():
            block = ""
            for k in range(nocells[2]):
                for i in range(nocells[0]):
                    block += f"{pvmult/(xcorc[i+1]-xcorc[i])} "
                block += "/\n" if k == nocells[2] - 1 else " "
            return block

        output += f"BOX\n1 1 1 {nocells[0]} 2* / \nMULTPV\n"
        output += multpv_block()
        output += "ENDBOX\n\n"

        output += f"BOX\n1 {nocells[0]} 1 1 2* / \nMULTPV\n"
        output += multpv_block()
        output += "ENDBOX\n\n"

        output += f"BOX\n{nocells[1]} {nocells[1]} 1 {nocells[0]} 2* / \nMULTPV\n"
        output += multpv_block()
        output += "ENDBOX\n\n"

        output += f"BOX\n1 {nocells[0]} {nocells[1]} {nocells[1]} 2* / \nMULTPV\n"
        output += multpv_block()
        output += "ENDBOX\n"

    return output


def generate_geology(dic):
    "Write geology.inc"
    output = ""

    nocells = dic["nocells"]
    dims = dic["dims"]

    if dic["grid"] == "cartesian2d":
        output += "INCLUDE\n"
        output += f"{dic['dx_file']} /\n\n"

        total = nocells[0] * nocells[1] * nocells[2]

        output += "DY\n"
        output += f"{total}*{dims[1]/nocells[1]} /\n\n"

        output += "DZ\n"
        if dic["homo"]:
            output += f"{total}*{dims[2]/nocells[2]} /\n"
        else:
            for i in range(dic["satnum"]):
                val = nocells[0] * nocells[1] * dic["rock"][i][4]
                thickness = dic["rock"][i][3] / dic["rock"][i][4]
                end = "/" if i == dic["satnum"] - 1 else ""
                output += f"{val}*{thickness} {end}"
        output += "\n\n"

        output += "TOPS\n"
        output += f"{nocells[0]*nocells[1]}*0 /\n"

    elif dic["grid"] == "core":
        total = nocells[0] * nocells[1] * nocells[2]

        output += "DX\n"
        output += f"{total}*{dims[0]/nocells[0]} /\n\n"

        output += "DY\n"
        output += f"{total}*{dims[2]/nocells[2]} /\n\n"

        output += "DZ\n"
        output += f"{total}*{dims[2]/nocells[2]} /\n\n"

        output += "TOPS\n"
        output += f"{nocells[0]*nocells[1]}*0 /\n"

    elif dic["grid"] == "radial":
        output += "INRAD\n"
        output += f"{dic['diameter']} /\n\n"

        output += "INCLUDE\n"
        output += f"{dic['drv_file']} /\n\n"

        output += "DTHETAV\n"
        output += f"{dims[1]} /\n\n"

        total = nocells[0] * nocells[1] * nocells[2]

        output += "DZ\n"
        if dic["homo"]:
            output += f"{total}*{dims[2]/nocells[2]} /\n"
        else:
            for i in range(dic["satnum"]):
                val = nocells[0] * nocells[1] * dic["rock"][i][4]
                thickness = dic["rock"][i][3] / dic["rock"][i][4]
                end = "/" if i == dic["satnum"] - 1 else ""
                output += f"{val}*{thickness} {end}"
        output += "\n\n"

        output += "TOPS\n"
        output += f"{nocells[0]}*0 /\n"

    elif dic["grid"] in ["cake", "tensor2d", "coord2d", "cpg3d"]:
        output += "INCLUDE\n"
        output += f"{dic['grid_file']} /\n"

    else:
        output += "INCLUDE\n"
        output += f"{dic['dx_file']} /\n\n"

        output += "INCLUDE\n"
        output += f"{dic['dy_file']} /\n\n"

        total = nocells[0] * nocells[1] * nocells[2]

        output += "DZ\n"
        if dic["homo"]:
            output += f"{total}*{dims[2]/nocells[2]} /\n"
        else:
            for i in range(dic["satnum"]):
                val = nocells[0] * nocells[1] * dic["rock"][i][4]
                thickness = dic["rock"][i][3] / dic["rock"][i][4]
                end = "/" if i == dic["satnum"] - 1 else ""
                output += f"{val}*{thickness} {end}"
        output += "\n\n"

        output += "TOPS\n"
        output += f"{nocells[0]*nocells[0]}*0 /\n"

    if dic["fluxnum"]:
        output += "\nEQUALREG\n"

        for j, name in zip([0, 0, 1, 2], ["PERMX", "PERMY", "PERMZ", "PORO "]):
            for i, rock in enumerate(dic["rock"]):
                spaces = " " * (dic["whsp"] - len(str(rock[j])))
                output += f"{name} {spaces}{rock[j]} {i+1} F /\n"

        output += "/\n"

    else:
        total = nocells[0] * nocells[1] * nocells[2]

        output += "\nPERMX\n"
        output += f"{total}*{dic['rock'][0][0]} /\n\n"

        output += "COPY \nPERMX PERMY /\n/\n\n"

        output += "PERMZ\n"
        output += f"{total}*{dic['rock'][0][1]} /\n\n"

        output += "PORO\n"
        output += f"{total}*{dic['rock'][0][2]} /\n"

    return output


def manage_sections(dic):
    """Write the include files in the input deck"""
    get_spaces(dic)
    fprep = dic["fprep"]
    result = generate_geology(dic)
    with open(
        os.path.join(fprep, "GEOLOGY.INC"),
        "w",
        encoding="utf-8",
    ) as f:
        f.write(HEADER)
        f.write(result)
    if dic["fluxnum"]:
        result = generate_fluxnum(dic)
        with open(
            os.path.join(fprep, "FLUXNUM.INC"),
            "w",
            encoding="utf-8",
        ) as f:
            f.write(HEADER)
            f.write(result)
    if dic["pvmult"] > 0:
        result = generate_multpv(dic)
        with open(
            os.path.join(fprep, "MULTPV.INC"),
            "w",
            encoding="utf-8",
        ) as f:
            f.write(HEADER)
            f.write(result)

    if dic["model"] in ["saltprec"] or dic["template"] in ["biofilm"]:
        result = generate_permfact(dic)
        with open(
            os.path.join(fprep, "PERMFACT.INC"),
            "w",
            encoding="utf-8",
        ) as f:
            f.writelines(HEADER)
            f.writelines(result)
        if dic["pcfact"] != 0:
            result = generate_pcfact(dic)
            with open(
                os.path.join(fprep, "PCFACT.INC"),
                "w",
                encoding="utf-8",
            ) as f:
                f.writelines(HEADER)
                f.writelines(result)


def generate_pcfact(dic):
    "Write pcfact.inc"

    names = [val[0] for val in dic["popevals"][0] if val[0] not in ["npoints"]]
    poro = compile(dic["poroperm"].strip(), "<string>", "eval")
    pcfact_exp = dic["pcfact"]

    safeglob = {"__builtins__": {}, "np": np}

    vals = [[0.0] * len(dic["popevals"][0]) for _ in range(len(dic["popevals"]))]

    for i in range(len(dic["popevals"])):
        for j in range(len(dic["popevals"][i])):
            vals[i][j] = dic["popevals"][i][j][1]

    lines = []
    lines.append("PCFACT\n")

    for i, para in enumerate(vals):
        if i > 0 and vals[i - 1] == para:
            lines.append("/\n")
            continue

        npoints = int(np.floor(para[-1]))
        pofas = np.linspace(para[0], 1, npoints)

        local_vars = {"pofa": pofas}
        for idx, name in enumerate(names):
            local_vars[name] = para[idx]

        poroperm_vals = eval(poro, safeglob, local_vars)  # pylint: disable=eval-used
        pcfact_vals = (pofas / poroperm_vals) ** pcfact_exp

        lines.append(f"0.0 {pcfact_vals[0]}\n")

        for pofa, val in zip(pofas, pcfact_vals):
            lines.append(f"{pofa} {val}\n")

        lines.append("/\n")

    for _ in range(len(dic["safu"]) - len(dic["popevals"])):
        lines.append("/\n")

    return lines


def generate_permfact(dic):
    "Write permfact.inc"

    names = [val[0] for val in dic["popevals"][0] if val[0] not in ["npoints"]]
    poro = compile(dic["poroperm"].strip(), "<string>", "eval")

    safeglob = {"__builtins__": {}, "np": np}

    vals = [[0.0] * len(dic["popevals"][0]) for _ in range(len(dic["popevals"]))]

    for i in range(len(dic["popevals"])):
        for j in range(len(dic["popevals"][i])):
            vals[i][j] = dic["popevals"][i][j][1]

    lines = []
    lines.append("PERMFACT\n")

    for i, para in enumerate(vals):
        if i > 0 and vals[i - 1] == para:
            lines.append("/\n")
            continue

        npoints = int(np.floor(para[-1]))
        pofas = np.linspace(para[0], 1, npoints)

        local_vars = {"pofa": pofas}
        for idx, name in enumerate(names):
            local_vars[name] = para[idx]

        poro_vals = eval(poro, safeglob, local_vars)  # pylint: disable=eval-used

        lines.append(f"0.0 {poro_vals[0]}\n")

        for pofa, val in zip(pofas, poro_vals):
            lines.append(f"{pofa} {val}\n")

        lines.append("/\n")

    for _ in range(len(dic["safu"]) - len(dic["popevals"])):
        lines.append("/\n")

    return lines


def get_spaces(dic):
    """Improve the format of the files by aligning the values"""
    dic["whsp"], dic["whnz"] = 0, 0
    if not dic["fluxnum"]:
        return
    dic["whnz"] = len(str(dic["nocells"][2]))
    whsp = dic["whsp"]
    for rock in dic["rock"]:
        for i in range(3):
            whsp = max(whsp, len(str(rock[i])))
    dic["whsp"] = whsp


def manage_tables(dic):
    """Write the saturation function tables"""
    model = dic["model"]
    template = dic["template"].lower()
    if model in ["co2store", "h2store", "saltprec"] and template != "h2ch4":
        result = generate_saturation_functions_format_2(dic)
    else:
        result = generate_saturation_functions_format_1(dic)
    with open(f"{dic['fprep']}/TABLES.INC", "w", encoding="utf8") as f:
        f.writelines(result)


def generate_saturation_functions_format_2(dic):
    "Using SGFN and SWFN"

    krw_code = compile(dic["krw"].strip(), "<string>", "eval")
    krn_code = compile(dic["krn"].strip(), "<string>", "eval")
    pcap_code = compile(dic["pcap"].strip(), "<string>", "eval")
    pcap_expr = dic["pcap"].strip()

    safeglob = {"__builtins__": {}, "np": np}

    safug = [[0.0] * len(dic["safu"][0]) for _ in range(len(dic["safu"]))]
    safuw = [[0.0] * len(dic["safu"][0]) for _ in range(len(dic["safu"]))]

    for i in range(len(dic["safu"])):
        for j in range(len(dic["safu"][i])):
            value = dic["safu"][i][j]
            safug[i][j] = value

            if dic["imbnum"] == 2 and j == 1 and len(dic["safu"]) / dic["imbnum"] <= i:
                idx = int(i % len(dic["safu"]) / dic["imbnum"])
                safuw[i][j] = dic["safu"][idx][j]
            else:
                safuw[i][j] = value

    lines = []
    lines.append("SGFN\n")

    for j, para in enumerate(safug):
        if j > 0 and safug[j - 1] == para:
            lines.append("/\n")
            continue

        swi = para[0]
        sni = para[1]
        krn = para[3]
        nkrn = para[6]

        sco2 = np.linspace(sni, 1 - swi, para[10])
        sw_values = 1 - sco2

        krn_vals = eval(  # pylint: disable=eval-used
            krn_code,
            safeglob,
            {
                "sw": sw_values,
                "swi": swi,
                "sni": sni,
                "krn": krn,
                "nkrn": nkrn,
            },
        )

        krn_vals = np.maximum(0, krn_vals)

        if sco2[0] > 0:
            lines.append(f"{0:E} {0:E} {0:E}\n")

        for i, value in enumerate(sco2[:-1]):
            lines.append(f"{value:E} {krn_vals[i]:E} {0:E} \n")

        lines.append(f"{sco2[-1]:E} {krn_vals[-1]:E} {0:E} \n")
        lines.append("/\n")

    lines.append("SWFN\n")

    for j, para in enumerate(safuw):
        if j > 0 and safuw[j - 1] == para:
            lines.append("/\n")
            continue

        swi = para[0]
        sni = para[1]
        krw = para[2]
        pen = para[4]
        nkrw = para[5]
        npen = para[7]
        sls = para[9]

        if sls in [1.0, 0.0]:
            swatc = np.linspace((1.0 - sls) * swi, 1, para[10])

            if pen == 0:
                pcw_vals = np.zeros_like(swatc)
            else:
                pcw_vals = eval(  # pylint: disable=eval-used
                    pcap_code,
                    safeglob,
                    {
                        "sw": swatc,
                        "swi": (1.0 - sls) * swi - para[8],
                        "sni": sni,
                        "pen": pen,
                        "npen": npen,
                    },
                )

            krw_vals = eval(  # pylint: disable=eval-used
                krw_code,
                safeglob,
                {
                    "sw": swatc,
                    "swi": swi,
                    "sni": sni,
                    "krw": krw,
                    "nkrw": nkrw,
                },
            )

            for i, value in enumerate(swatc):
                if value <= swi:
                    lines.append(f"{value:E} {0:E} {pcw_vals[i]:E} \n")
                elif value >= 1 - sni:
                    lines.append(f"{value:E} {1:E} {pcw_vals[i]:E} \n")
                else:
                    lines.append(f"{value:E} {krw_vals[i]:E} {pcw_vals[i]:E} \n")

        else:
            swatc = np.linspace(0, 1, para[10])

            krw_vals = eval(  # pylint: disable=eval-used
                krw_code,
                safeglob,
                {
                    "sw": swatc,
                    "swi": swi,
                    "sni": sni,
                    "krw": krw,
                    "nkrw": nkrw,
                },
            )

            krw_vals_low = eval(  # pylint: disable=eval-used
                krw_code,
                safeglob,
                {
                    "sw": np.maximum(swatc, swi),
                    "swi": swi,
                    "sni": sni,
                    "krw": krw,
                    "nkrw": nkrw,
                },
            )

            if pen == 0:
                pcw_vals = np.zeros_like(swatc)
                pc_sls = 0
            else:
                pcw_vals = eval(  # pylint: disable=eval-used
                    pcap_code,
                    safeglob,
                    {
                        "sw": swatc,
                        "swi": swi,
                        "sni": sni,
                        "pen": pen,
                        "npen": npen,
                    },
                )

                pc_sls = eval(  # pylint: disable=eval-used
                    pcap_code,
                    safeglob,
                    {
                        "sw": sls,
                        "swi": swi,
                        "sni": sni,
                        "pen": pen,
                        "npen": npen,
                    },
                )

            if (
                pcap_expr
                == "pen * (((sw - swi) / (1. - swi)) ** (-(1./npen)) - 1.) ** (1. - npen)"
            ):
                cap_vals = 10.0 ** (
                    (sls - swatc)
                    * np.log(
                        (sls)
                        / (sls - swi)
                        * ((1.0 - npen) / npen)
                        * (1.0 / (1.0 - ((sls - swi) / (1 - swi)) ** (1.0 / npen)))
                    )
                    / sls
                    + np.log10(pc_sls)
                )
            else:
                cap_vals = 10.0 ** (
                    (sls - swatc) * np.log((sls) / ((sls - swi) * npen)) / sls
                    + np.log10(pc_sls)
                )

            for i, value in enumerate(swatc):
                if value <= sls:
                    lines.append(f"{value:E} {krw_vals_low[i]:E} {cap_vals[i]:E} \n")
                elif value >= 1 - sni:
                    lines.append(f"{value:E} {1:E} {pcw_vals[i]:E} \n")
                else:
                    lines.append(f"{value:E} {krw_vals[i]:E} {pcw_vals[i]:E} \n")

        lines.append("/\n")

    return lines


def generate_saturation_functions_format_1(dic):
    "Using SGOF"

    krw_code = compile(dic["krw"].strip(), "<string>", "eval")
    krn_code = compile(dic["krn"].strip(), "<string>", "eval")
    pcap_code = compile(dic["pcap"].strip(), "<string>", "eval")

    safeglob = {"__builtins__": {}, "np": np}

    safu = [[0.0] * len(dic["safu"][0]) for _ in range(len(dic["safu"]))]

    for i in range(len(dic["safu"])):
        for j in range(len(dic["safu"][i])):
            safu[i][j] = dic["safu"][i][j]

    lines = []
    lines.append("SGOF\n")

    for j, para in enumerate(safu):
        if j > 0 and safu[j - 1] == para:
            lines.append("/\n")
            continue

        swi = para[0]
        sni = para[1]
        krw = para[2]
        krn = para[3]
        pen = para[4]
        nkrw = para[5]
        nkrn = para[6]
        npen = para[7]

        snatc = np.linspace(sni, 1 - swi, para[10])
        sw_values = 1 - snatc
        pc_sw_values = sw_values + para[8]

        krw_vals = eval(  # pylint: disable=eval-used
            krw_code,
            safeglob,
            {
                "sw": sw_values,
                "swi": swi,
                "sni": sni,
                "krw": krw,
                "nkrw": nkrw,
            },
        )

        krn_vals = eval(  # pylint: disable=eval-used
            krn_code,
            safeglob,
            {
                "sw": sw_values,
                "swi": swi,
                "sni": sni,
                "krn": krn,
                "nkrn": nkrn,
            },
        )

        if pen == 0:
            pc_vals = np.zeros_like(sw_values)
        else:
            pc_vals = eval(  # pylint: disable=eval-used
                pcap_code,
                safeglob,
                {
                    "sw": pc_sw_values,
                    "swi": swi,
                    "sni": sni,
                    "pen": pen,
                    "npen": npen,
                },
            )

        if sni > 0:
            lines.append(f"{0:E} {0:E} {1:E} {pc_vals[0]:E} \n")

        for i, value in enumerate(snatc):
            if i == 0:
                lines.append(f"{value:E} {0:E} {krw_vals[i]:.6f} {pc_vals[i]:E} \n")
            else:
                lines.append(
                    f"{value:E} {krn_vals[i]:.6f} {krw_vals[i]:.6f} {pc_vals[i]:E} \n"
                )

        lines.append("/\n")

    return lines


def manage_grid(dic):
    """Handle the grid"""
    grid = dic["grid"]
    nocells = dic["nocells"]
    if grid == "cartesian2d":
        dxarray = np.diff(dic["xcor"])
        dxarray = np.tile(dxarray, nocells[2])
        dxarray = compact_format(dxarray)
        dxarray.insert(0, "DX\n")
        dxarray.append("/")
        with open(
            os.path.join(dic["fprep"], "DX.INC"),
            "w",
            encoding="utf8",
        ) as file:
            file.write("".join(dxarray))
    elif grid == "radial":
        dxarray = compact_format(np.diff(dic["xcor"]))
        dxarray.insert(0, "DRV\n")
        dxarray.append("/")
        with open(
            os.path.join(dic["fprep"], "DRV.INC"),
            "w",
            encoding="utf8",
        ) as file:
            file.write("".join(dxarray))
    elif grid in ["cake", "tensor2d", "coord2d"]:
        dic["slope"] = np.tan(0.5 * dic["dims"][1] * np.pi / 180)
        get_2dgrid(dic)
    else:
        if grid == "coord3d":
            dic["xcorc"] = dic["xcn"]
        else:
            create_3dgrid(dic)
            if dic["model"] not in ["co2eor", "foam"]:
                xcorc = dic["xcorc"]
                dic["xcorc"] = np.concatenate((-xcorc[::-1], xcorc))
        dic["xcorc"] = np.asarray(dic["xcorc"])
        dxarray = np.diff(dic["xcorc"])
        nocells[0] = len(dic["xcorc"]) - 1
        nocells[1] = nocells[0]
        d3_grids(dic, dxarray)


def round_like_e(v: NDArray) -> NDArray:
    """Keep only 8 significant digits to reduce size of created files"""
    return np.asarray([float(f"{x:E}") for x in v])


def get_2dgrid(dic):
    """Create the 2D corner-point grid"""
    grid = []
    xcor = dic["xcor"]
    slope = dic["slope"]
    dims = dic["dims"]
    grid.append("COORD\n")

    xx = np.tile(xcor, 2)
    yy = np.concatenate([-xcor * slope, xcor * slope])

    values = np.column_stack(
        (
            xx,
            yy,
            np.zeros_like(xx),
            xx,
            yy,
            np.full_like(xx, dims[2]),
        )
    ).ravel()
    grid += compact_format(round_like_e(values))
    grid.append("/\n")
    grid.append("ZCORN\n")
    mainfold = compile(dic["zxy"], "<string>", "eval")
    xf = eval(  # pylint: disable=eval-used
        mainfold,
        {"__builtins__": {}, "np": np},
        {"x": xcor},
    )
    nx, ny, nz = dic["nocells"]
    pairs = np.column_stack((xf[:-1], xf[1:]))
    total = 8 * nx * ny * nz
    grids = np.empty(total, dtype=pairs.dtype)
    p = 0
    block = pairs.ravel()
    nrep = 2 * ny
    size = nrep * block.size
    grids[p : p + size] = np.tile(block, nrep)
    p += size
    dz = dims[2] / nz
    for k in range(1, nz):
        zshift = k * dz
        block = (pairs + zshift).ravel()
        nrep = 4 * ny
        size = nrep * block.size
        grids[p : p + size] = np.tile(block, nrep)
        p += size
    block = (pairs + dims[2]).ravel()
    nrep = 2 * ny
    size = nrep * block.size
    grids[p : p + size] = np.tile(block, nrep)
    grid += compact_format(round_like_e(grids))
    with open(
        os.path.join(dic["fprep"], "GRID.INC"),
        "w",
        encoding="utf8",
    ) as f:
        f.write(HEADER)
        f.write("".join(grid))
        f.write("/\n")


def compact_format(v: NDArray) -> list[str]:
    "To 'n*x' notation"
    v = np.array(v)
    change_idx = np.flatnonzero(np.diff(v, prepend=v[0] - 1))
    counts = np.diff(np.append(change_idx, v.size))
    vals = v[change_idx]

    out = []
    for val, n in zip(vals, counts):
        val_str = str(int(val)) if float(val).is_integer() else str(val)
        out.append(f"{n}*{val_str} " if n > 1 else f"{val_str} ")
    return out


def handle_core(dic):
    """Handle the core geometry"""
    nocells = dic["nocells"]
    dims = dic["dims"]
    xcenters = (np.arange(nocells[0]) + 0.5) * dims[0] / nocells[0]
    zcenters = (np.arange(nocells[2]) + 0.5) * dims[2] / nocells[2] - 0.5 * dims[2]
    edge = (xcenters < dims[1]) | (xcenters > dims[0] - dims[1])
    radius2 = zcenters[:, None] ** 2 + zcenters[None, :] ** 2
    small2 = (0.5 * dims[2] / nocells[2]) ** 2
    large2 = (0.5 * dims[2]) ** 2
    active = np.where(
        edge[None, None, :],
        radius2[:, :, None] <= small2,
        radius2[:, :, None] <= large2,
    ).ravel()
    changes = np.flatnonzero(active[1:] != active[:-1]) + 1
    starts = np.concatenate(([0], changes))
    ends = np.concatenate((changes, [len(active)]))
    dic["coregeometry"] = ["MULTPV\n"]
    for start, end in zip(starts, ends):
        count = end - start
        dic["coregeometry"].append(f"{count}* " if active[start] else f"{count}*0 ")
    dic["coregeometry"].append("/")
    dims[1] = dims[2]
    nocells[1] = nocells[2]


def d3_grids(dic, dxarray):
    """Handle the second part of the 3d grids"""
    grid_name = dic["grid"]
    if grid_name == "cpg3d":
        grid = []
        xcorc = dic["xcorc"]
        grid.append("COORD\n")
        xx, yy = np.meshgrid(xcorc, xcorc, indexing="xy")
        grid += compact_format(
            np.column_stack(
                (
                    xx.ravel(),
                    yy.ravel(),
                    np.zeros(xx.size),
                    xx.ravel(),
                    yy.ravel(),
                    np.zeros(xx.size),
                )
            ).ravel()
        )
        grid.append("/\n")
        grid.append("ZCORN\n")
        mainfold_code = compile(dic["zxy"], "<string>", "eval")

        def mainfold(x, y):
            return eval(  # pylint: disable=eval-used
                mainfold_code,
                {"__builtins__": {}, "np": np},
                {"x": x, "y": y},
            )

        x = np.asarray(dic["xcorc"])
        nx, ny, nz = dic["nocells"]
        dims = dic["dims"]
        x0 = x[:-1]
        x1 = x[1:]
        y0 = x[:-1]
        y1 = x[1:]
        a0 = mainfold(x0[None, :], y0[:, None])
        a1 = mainfold(x1[None, :], y0[:, None])
        b0 = mainfold(x0[None, :], y1[:, None])
        b1 = mainfold(x1[None, :], y1[:, None])
        row0 = np.stack((a0, a1), axis=-1)
        row1 = np.stack((b0, b1), axis=-1)
        base = np.empty((ny, 2, nx, 2), dtype=row0.dtype)
        base[:, 0, :, :] = row0
        base[:, 1, :, :] = row1
        bottom = base.reshape(-1)
        if dic["model"] in ["co2eor", "foam"]:
            zvals = np.asarray(dic["zcords"][1:])
        else:
            zvals = np.arange(1, nz) * dims[2] / nz
        interior = base[None, None, :, :, :, :] + zvals[:, None, None, None, None, None]
        interior = np.broadcast_to(interior, (nz - 1, 2, ny, 2, nx, 2)).reshape(-1)
        top = (base + dims[2]).reshape(-1)
        grids = np.concatenate([bottom, interior, top])

        grid += compact_format(round_like_e(grids))

        with open(
            os.path.join(dic["fprep"], "GRID.INC"),
            "w",
            encoding="utf8",
        ) as f:
            f.write(HEADER)
            f.write("".join(grid))
            f.write("/\n")
    else:
        if dic["model"] in ["co2eor", "foam"]:
            return
        nocells = dic["nocells"]
        dxarray = np.asarray(dxarray)
        dyarray = np.repeat(dxarray[: nocells[1]], nocells[1])
        dxarray = np.tile(dxarray, nocells[1])
        if nocells[2] > 1:
            dxarray = np.tile(dxarray, nocells[2])
            dyarray = np.tile(dyarray, nocells[2])
        with open(
            f"{dic['fprep']}/DX.INC",
            "w",
            encoding="utf8",
        ) as f:
            f.write(HEADER)
            f.write("DX\n")
            f.write("".join(compact_format(dxarray)))
            f.write("/\n")
        with open(
            f"{dic['fprep']}/DY.INC",
            "w",
            encoding="utf8",
        ) as f:
            f.write(HEADER)
            f.write("DY\n")
            f.write("".join(compact_format(dyarray)))
            f.write("/\n")


def create_3dgrid(dic):
    """Handle the first part of the 3d grids"""
    xfac = dic["xfac"]
    dims = dic["dims"]
    nocells = dic["nocells"]
    if xfac != 0:
        dic["xcorc"] = np.flip(
            dims[0]
            * (np.exp(np.flip(np.linspace(0, xfac, nocells[0] + 1))) - 1)
            / (np.exp(xfac) - 1)
        )
        if dic["removecells"] == 1:
            xcorc = dic["xcorc"]
            dic["xcorc"] = xcorc[(dic["diameter"] < xcorc) | (0 == xcorc)]
        dic["xcorc"][0] = 0.25 * dic["xcorc"][1]
    elif dic["grid"] == "tensor3d":
        xcn = dic["xcn"]
        dims0 = dims[0]
        xcn_len = len(xcn)
        xcn_len2 = len(2 * xcn)
        segments = []
        for j, num in enumerate(xcn):
            if j == 0:
                values = np.arange(num + 1, dtype=float)
                segment = ((values + 1 + num) / (2 * num + 1)) * (
                    2 * dims0 / xcn_len2
                ) - (dims0 / xcn_len2)
            else:
                values = np.arange(1, num + 1, dtype=float)
                segment = (j + values / num) * dims0 / xcn_len
            segments.append(segment)
        dic["xcorc"] = np.concatenate(segments)
    else:
        dic["xcorc"] = np.linspace(0, dims[0], nocells[0] + 1)
        if dic["removecells"] == 1:
            xcorc = dic["xcorc"]
            dic["xcorc"] = xcorc[(dic["diameter"] < xcorc) | (0 == xcorc)]
        if dic["model"] not in ["co2eor", "foam"]:
            dic["xcorc"][0] = 0.25 * dic["xcorc"][1]
        else:
            dic["zcords"] = [0.0]
            rock = dic["rock"]
            for i in range(dic["satnum"]):
                for _ in range(rock[i][4]):
                    dic["zcords"].append(dic["zcords"][-1] + rock[i][3] / rock[i][4])
