#Set mpirun, the full path to the flow executable, and simulator flags (except --output-dir)
flow = "flow --relaxed-max-pv-fraction=0 --enable-opm-rst-file=true --newton-min-iterations=1 --enable-tuning=true"

#Set the model parameters
model = "co2eor" #Model (co2store/co2eor/foam/h2store/saltprec)
template = "lowerlayerinjection" #Template file (see src/pyopmnearwell/templates/)
grid = "cpg3d" #Grid type (radial/cake/cartesian2d/cartesian/cave/coord2d/coord3d/tensor2d/tensor3d)
xdim = 3500 #Length [ft] (for cartesian/cpg3d/coord3d/tensor3d, Length=Width=2*xdim)
xcn = [21] #Number of x-cells [-]; coordinates for grid type coord2d/coord3d [m]; numbers of x-cells for grid type tensor2d/tensor3d [-] 
diameter = 0.5 #Well diameter [ft]
pressure = 4000 #Pressure [Psia] on the top
injbhp = 9000 #Injector max BHP [Psia]
probhp = 1500 #Producer min BHP [Psia]
zxy = "8325 + (20-20*mt.cos((2*mt.pi*(x+y)/3000)))" #The function for the reservoir surface

#Properties rock: 1) Kxy [mD], 2) Kz [mD], 3) phi [-], 4) thickness [ft], and 5) no cells in the z dir [-] (entry per layer)
rock = [[500,50,0.3,20,10],[50,50,0.3,30,6],[200,25,0.3,50,5]]

#Define the injection values (entry per change in the schedule): 
#1) injection time [d], 2) time step size to write results [d], 3) maximum time step [d]
#4) fluid (0 wetting, 1 non-wetting), 5) injection rates [stb/day]
inj=[[90,30,1,0,1200],[90,30,1,1,12000],[90,30,1,0,1200],[90,30,1,1,12000],[90,30,1,0,1200],[90,30,1,1,12000],[90,30,1,0,1200],[90,30,1,1,12000]]